#!/usr/bin/env bash
# Compile all Python requirements
set -e

CLAIR_INDEX_URL=https://gitlab.smhi.se/api/v4/projects/3495/packages/pypi/simple

echo updating "requirements.txt"
pip-compile --quiet --allow-unsafe --generate-hashes --strip-extras --extra-index-url=${CLAIR_INDEX_URL} \
	setup.cfg --output-file requirements.txt
chmod 644 requirements.txt
echo updating "requirements-dev.txt"
pip-compile --quiet --allow-unsafe --generate-hashes \
	--resolver backtracking --no-strip-extras \
	requirements-dev.in -c requirements.txt --output-file requirements-dev.txt
chmod 644 requirements-dev.txt
