# Generated by Django 3.2.18 on 2023-05-09 14:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import etk.edb.ltreefield
import etk.edb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name of activity')),
                ('unit', models.CharField(max_length=100, verbose_name='unit of activity')),
            ],
            options={
                'default_related_name': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='slug')),
                ('srid', models.IntegerField(help_text='Spatial reference system identifier', verbose_name='SRID')),
                ('extent', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326, verbose_name='extent')),
                ('timezone', models.CharField(max_length=64, verbose_name='timezone')),
            ],
            options={
                'db_table': 'domains',
                'default_related_name': 'domains',
            },
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='slug')),
                ('long_name', models.CharField(max_length=64, verbose_name='long name')),
            ],
            options={
                'db_table': 'substances',
                'default_related_name': 'substances',
            },
        ),
        migrations.CreateModel(
            name='VerticalDist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('weights', models.CharField(default=etk.edb.models.default_vertical_dist, max_length=100)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertical_dists', to='edb.domain')),
            ],
            options={
                'unique_together': {('domain', 'name'), ('domain', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CodeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_sets', to='edb.domain')),
            ],
            options={
                'unique_together': {('domain', 'name'), ('domain', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ActivityCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', etk.edb.ltreefield.LtreeField(verbose_name='activity code')),
                ('label', models.CharField(max_length=100, verbose_name='activity code label')),
                ('code_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='edb.codeset')),
                ('vertical_dist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edb.verticaldist')),
            ],
        ),
        migrations.AddConstraint(
            model_name='activitycode',
            constraint=models.UniqueConstraint(fields=('code_set', 'code'), name='unique code in codeset'),
        ),
    ]
