# Generated by Django 3.2.18 on 2023-05-17 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=64, unique=True, verbose_name="slug"),
                ),
                (
                    "quantity",
                    models.CharField(max_length=30, verbose_name="physical quantity"),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="edb.substance",
                        verbose_name="substance",
                    ),
                ),
            ],
            options={
                "db_table": "parameters",
                "default_related_name": "parameters",
            },
        ),
    ]
