# Generated by Django 4.2.2 on 2023-06-20 14:31

import django.db.models.deletion
from django.db import migrations, models

import etk.edb.ltreefield


class Migration(migrations.Migration):

    dependencies = [
        ("edb", "0002_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="EEAEmissionFactor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nfr_code", etk.edb.ltreefield.LtreeField(verbose_name="NFR code")),
                ("sector", models.CharField(max_length=100)),
                (
                    "table",
                    models.CharField(
                        max_length=100, verbose_name="table in EMEP/EEA Guidebook 2019"
                    ),
                ),
                ("tier", models.CharField(max_length=100)),
                ("technology", models.CharField(max_length=100)),
                ("fuel", models.CharField(max_length=100)),
                ("abatement", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                (
                    "value",
                    models.FloatField(
                        default=0, verbose_name="best estimate emission factor"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        max_length=100, verbose_name="unit of emission factor value"
                    ),
                ),
                (
                    "lower",
                    models.FloatField(
                        default=0,
                        verbose_name="lower confidence interval emission factor",
                    ),
                ),
                (
                    "upper",
                    models.FloatField(
                        default=0,
                        verbose_name="upper confidence interval emission factor",
                    ),
                ),
                ("reference", models.CharField(max_length=100)),
                (
                    "substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="edb.substance",
                    ),
                ),
            ],
            options={
                "default_related_name": "eea_emissionfactors",
            },
        ),
    ]
