# Generated by Django 3.2.18 on 2023-06-06 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edb", "0003_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointSourceActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.FloatField(verbose_name="activity rate")),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="edb.activity",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="edb.pointsource",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "activities",
            },
        ),
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("factor", models.FloatField(default=0)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emissionfactors",
                        to="edb.activity",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="edb.substance",
                    ),
                ),
            ],
            options={
                "default_related_name": "emissionfactors",
            },
        ),
        migrations.AddConstraint(
            model_name="pointsourceactivity",
            constraint=models.UniqueConstraint(
                fields=("source", "activity"),
                name="pointsourceactivity_unique_activity_in_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="emissionfactor",
            constraint=models.UniqueConstraint(
                fields=("activity", "substance"),
                name="emissionfactor_activity_substance_unique_together",
            ),
        ),
    ]
