# Generated by Django 4.2.2 on 2023-09-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edb", "0003_eeaemissionfactor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codeset",
            options={"default_related_name": "codesets"},
        ),
        migrations.AlterModelOptions(
            name="verticaldist",
            options={"default_related_name": "vertical_distributions"},
        ),
        migrations.AlterUniqueTogether(
            name="codeset",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="verticaldist",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="codeset",
            name="slug",
            field=models.SlugField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="verticaldist",
            name="slug",
            field=models.SlugField(max_length=64, unique=True),
        ),
        migrations.AlterModelTable(
            name="codeset",
            table="codesets",
        ),
        migrations.AlterModelTable(
            name="verticaldist",
            table="vertical_distributions",
        ),
        migrations.RemoveField(
            model_name="codeset",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="verticaldist",
            name="domain",
        ),
        migrations.DeleteModel(
            name="Domain",
        ),
    ]
