# Generated by Django 4.2.2 on 2023-06-14 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edb", "0004_sourceactivity"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pointsource",
            new_name="pointsource_activities_idx",
            old_fields=("activitycode1", "activitycode2", "activitycode3"),
        ),
        migrations.AlterField(
            model_name="emissionfactor",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="edb.activity"
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="substance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="edb.substance",
                verbose_name="substance",
            ),
        ),
        migrations.AlterField(
            model_name="pointsource",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="edb.facility",
            ),
        ),
        migrations.AlterField(
            model_name="pointsourceactivity",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="edb.pointsource"
            ),
        ),
        migrations.AlterField(
            model_name="pointsourcesubstance",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="edb.pointsource"
            ),
        ),
    ]
