# Generated by Django 3.2.19 on 2023-06-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edb", "0004_sourceactivity"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="pointsource",
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name="pointsource",
            index=models.Index(
                fields=["activitycode1", "activitycode2", "activitycode3"],
                name="pointsource_activities_idx",
            ),
        ),
    ]
