# Generated by Django 4.2.2 on 2023-09-06 10:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edb", "0004_delete_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "srid",
                    models.IntegerField(
                        help_text="Spatial reference system identifier",
                        verbose_name="SRID",
                    ),
                ),
                (
                    "extent",
                    django.contrib.gis.db.models.fields.PolygonField(
                        geography=True, srid=4326, verbose_name="extent"
                    ),
                ),
                ("timezone", models.CharField(max_length=64, verbose_name="timezone")),
                (
                    "primary_codeset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_codeset",
                        to="edb.codeset",
                    ),
                ),
            ],
            options={
                "db_table": "settings",
                "default_related_name": "settings",
            },
        ),
    ]
