# Generated by Django 4.2.4 on 2023-09-13 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edb", "0005_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="primary_codeset",
        ),
        migrations.AddField(
            model_name="settings",
            name="codeset1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="edb.codeset",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="codeset2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="edb.codeset",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="codeset3",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="edb.codeset",
            ),
        ),
    ]
