# Generated by Django 4.2.2 on 2023-10-26 10:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edb", "0006_remove_settings_primary_codeset_settings_codeset1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time of creation"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="time of last update"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="user-defined key-value pairs",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PolygonField(
                        db_index=True,
                        geography=True,
                        srid=4326,
                        verbose_name="the extent of the area source",
                    ),
                ),
                (
                    "activitycode1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="edb.activitycode",
                    ),
                ),
                (
                    "activitycode2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="edb.activitycode",
                    ),
                ),
                (
                    "activitycode3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="edb.activitycode",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="edb.facility",
                    ),
                ),
                (
                    "timevar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="edb.timevar",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "areasources",
            },
        ),
        migrations.CreateModel(
            name="AreaSourceActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.FloatField(verbose_name="activity rate")),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="edb.activity",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="edb.areasource"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "activities",
            },
        ),
        migrations.CreateModel(
            name="AreaSourceSubstance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(default=0, verbose_name="source emission")),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date of last update"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="edb.areasource"
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="edb.substance",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "substances",
                "unique_together": {("source", "substance")},
            },
        ),
        migrations.AddConstraint(
            model_name="areasourceactivity",
            constraint=models.UniqueConstraint(
                fields=("source", "activity"),
                name="areasourceactivity_unique_activity_in_source",
            ),
        ),
        migrations.AddIndex(
            model_name="areasource",
            index=models.Index(
                fields=["activitycode1", "activitycode2", "activitycode3"],
                name="areasource_activities_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="areasource",
            constraint=models.UniqueConstraint(
                fields=("facility", "name"), name="areasource_unique_facility_and_name"
            ),
        ),
    ]
