name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - uses: pre-commit/action@v3.0.1

      - uses: astral-sh/setup-uv@v10.1.0

      - name: Install build
        run: uv pip install --system -c requirements-dev.txt build

      - name: Build dist
        run: python -m build

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install GDAL dependencies
        run: |
          sudo apt update
          sudo apt install -y gdal-bin libgdal-dev python3-gdal libsqlite3-mod-spatialite

      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - uses: astral-sh/setup-uv@v10.1.0

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          path: dist/
          merge-multiple: true

      - name: Install nox
        run: uv pip install --system -c requirements-dev.txt nox

      - name: Django checks
        run: nox -s django

      - name: Migrations
        env:
          SPATIALITE_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/mod_spatialite.so
        run: nox -s migrations

      - name: Test (lowest)
        env:
          SPATIALITE_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/mod_spatialite.so
        run: nox -s test-lowest -- --cov --durations=20 --junit-xml=junit-lowest.xml

      - name: Test (latest)
        env:
          SPATIALITE_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/mod_spatialite.so
        run: nox -s test -- --cov --durations=20 --junit-xml=junit-latest.xml

      - name: Test Report
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() && github.event_name == 'pull_request' }}       # run this step even if previous step failed
        with:
          name: test-results
          path: junit-*.xml
          reporter: jest-junit
